json.extract! socioeduk_saude_jovens_tipo_parentesco_doenca_mental, :id, :socioeduk_saude_jovens_id, :socioeduk_tipo_parentesco_id, :created_at, :updated_at
json.url socioeduk_saude_jovens_tipo_parentesco_doenca_mental_url(socioeduk_saude_jovens_tipo_parentesco_doenca_mental, format: :json)
