module Bairros
  def self.popular
    puts "Importando Bairros ..."
    Bairro.find_or_create_by(cidade_id:'620', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'620', nome:'Alto da Alegria')
    Bairro.find_or_create_by(cidade_id:'620', nome:'Populares')
    Bairro.find_or_create_by(cidade_id:'620', nome:'Capoeiras')
    Bairro.find_or_create_by(cidade_id:'623', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'623', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'623', nome:'Nova Acopiara')
    Bairro.find_or_create_by(cidade_id:'623', nome:'Vila Palmeira')
    Bairro.find_or_create_by(cidade_id:'623', nome:'Moreiras')
    Bairro.find_or_create_by(cidade_id:'623', nome:'Bom Sucesso')
    Bairro.find_or_create_by(cidade_id:'623', nome:'Vila Esperança')
    Bairro.find_or_create_by(cidade_id:'623', nome:'Vila São João')
    Bairro.find_or_create_by(cidade_id:'623', nome:'Nossa Senhora Aparecida')
    Bairro.find_or_create_by(cidade_id:'625', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'625', nome:'Junco')
    Bairro.find_or_create_by(cidade_id:'625', nome:'Caldeirão')
    Bairro.find_or_create_by(cidade_id:'625', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'625', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'627', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'627', nome:'Alípios')
    Bairro.find_or_create_by(cidade_id:'627', nome:'Menino Deus')
    Bairro.find_or_create_by(cidade_id:'627', nome:'Jardim')
    Bairro.find_or_create_by(cidade_id:'627', nome:'Tibolo')
    Bairro.find_or_create_by(cidade_id:'627', nome:'Pão de Açúcar')
    Bairro.find_or_create_by(cidade_id:'627', nome:'Dom Pompeu')
    Bairro.find_or_create_by(cidade_id:'632', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'632', nome:'Farias Brito')
    Bairro.find_or_create_by(cidade_id:'632', nome:'Pedregal')
    Bairro.find_or_create_by(cidade_id:'632', nome:'Nossa Senhora de Fátima')
    Bairro.find_or_create_by(cidade_id:'632', nome:'Córrego dos Rodrigues')
    Bairro.find_or_create_by(cidade_id:'632', nome:'Campo Verde')
    Bairro.find_or_create_by(cidade_id:'632', nome:'Aterro')
    Bairro.find_or_create_by(cidade_id:'632', nome:'Nossa Senhora de Lourdes')
    Bairro.find_or_create_by(cidade_id:'632', nome:'Várzea da Matriz')
    Bairro.find_or_create_by(cidade_id:'634', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'634', nome:'Planalto')
    Bairro.find_or_create_by(cidade_id:'634', nome:'Ferreirão')
    Bairro.find_or_create_by(cidade_id:'634', nome:'Beira Rio')
    Bairro.find_or_create_by(cidade_id:'634', nome:'Varjota')
    Bairro.find_or_create_by(cidade_id:'637', nome:'Arneirozinho')
    Bairro.find_or_create_by(cidade_id:'637', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'637', nome:'Cecília Alves Bezerra')
    Bairro.find_or_create_by(cidade_id:'637', nome:'Dr. Lanes Leal Petrola')
    Bairro.find_or_create_by(cidade_id:'637', nome:'Santo Antônio')
    Bairro.find_or_create_by(cidade_id:'637', nome:'Silva Bezerra')
    Bairro.find_or_create_by(cidade_id:'639', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'639', nome:'José Fernandes Campos')
    Bairro.find_or_create_by(cidade_id:'639', nome:'Mororó')
    Bairro.find_or_create_by(cidade_id:'639', nome:'Recreio')
    Bairro.find_or_create_by(cidade_id:'639', nome:'Araçá')
    Bairro.find_or_create_by(cidade_id:'639', nome:'José Leite Figueiredo - Zezé da Cruz')
    Bairro.find_or_create_by(cidade_id:'639', nome:'Vila Paulo Gonçalves')
    Bairro.find_or_create_by(cidade_id:'639', nome:'José Freire do Amaral')
    Bairro.find_or_create_by(cidade_id:'639', nome:'São Benedito')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Rosário')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Tupinambá')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Santo Antônio')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Nossa Senhora de Fátima')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Alto da Alegria')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Bulandeira')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Mata dos Limas')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Buriti')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Malvinas')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Santo André')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Cirolândia')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Alto do Rosário')
    Bairro.find_or_create_by(cidade_id:'642', nome:'Mata dos Dudas')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Poço da Pedra')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Jardim Raimundo Inácio')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Gangorra')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'644', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Baixio Velho')
    Bairro.find_or_create_by(cidade_id:'644', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Xique-Xique')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Muquém')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Trajano Nogueira')
    Bairro.find_or_create_by(cidade_id:'644', nome:'Aurílio Cardoso')
    Bairro.find_or_create_by(cidade_id:'645', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'645', nome:'Nossa Senhora dos Navegantes')
    Bairro.find_or_create_by(cidade_id:'645', nome:'Poço Imperial')
    Bairro.find_or_create_by(cidade_id:'645', nome:'Caucaia')
    Bairro.find_or_create_by(cidade_id:'645', nome:'Carmelita Veras')
    Bairro.find_or_create_by(cidade_id:'645', nome:'Jaime Laurindo')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Coió')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Comendador Ananias Arruda')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Conjunto Habitacional Maria José Viana')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Conselheiro Estelita')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Feira do Gado')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Gustavo Sampaio')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Jesuítas')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Manga')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Mondego')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Mucunã')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Nossa Senhora Auxiliadora')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Putiú')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Sanharão')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Vila Nova')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'646', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'646', nome:'Beira Rio')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Vila Azul')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Alto do Motor')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Boaviaginha')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Recreio')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Alto da Queiroz')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Ponte Nova')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Vila Holanda')
    Bairro.find_or_create_by(cidade_id:'649', nome:'José Rosa')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Fátima')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Tibiquari')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Floresta')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Várzea do Canto')
    Bairro.find_or_create_by(cidade_id:'649', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Aldeota')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Morro Dourado')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Sol Nascente')
    Bairro.find_or_create_by(cidade_id:'650', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Cabaceiras')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Eliseu Gomes de Lucena')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Renê Lucena')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Raimundo Fernandes')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Araujão')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Capilé')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Luzia Leite')
    Bairro.find_or_create_by(cidade_id:'650', nome:'Taboqueiras')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Alto Guaramiranga')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Boa Vista')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Canindezinho')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Capitão Pedro Sampaio')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Imaculada Conceição')
    Bairro.find_or_create_by(cidade_id:'653', nome:'João Paulo II')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Jubaia')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Nossa Senhora das Graças')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Palestina')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Riacho São Francisco')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Santa Luzia')
    Bairro.find_or_create_by(cidade_id:'653', nome:'São Mateus')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Santa Clara')
    Bairro.find_or_create_by(cidade_id:'653', nome:'Campinas')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Centro - do distrito de Caridade')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Pé do Serrote')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Coração de Jesus')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Açude Novo')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Conjunto')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Alto da Bela Vista')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Alto da Delegacia')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Estrada Vila Nova')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Centro - do distrito de Campos Belos')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Vila Beta')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Açudinho')
    Bairro.find_or_create_by(cidade_id:'655', nome:'Três Bocas')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Mestre Neco')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Nossa Senhora do Carmo')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Paraíso')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Umari')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Pernambuquinho')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Padre Cícero')
    Bairro.find_or_create_by(cidade_id:'657', nome:'José Agostinho')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Palestina')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Abílio Unias')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Cedron')
    Bairro.find_or_create_by(cidade_id:'657', nome:'Bico da Arara')
    Bairro.find_or_create_by(cidade_id:'658', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'658', nome:'São Vicente')
    Bairro.find_or_create_by(cidade_id:'658', nome:'Vila Nova')
    Bairro.find_or_create_by(cidade_id:'658', nome:'Esplanada')
    Bairro.find_or_create_by(cidade_id:'658', nome:'Acampamento')
    Bairro.find_or_create_by(cidade_id:'662', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'662', nome:'Açude')
    Bairro.find_or_create_by(cidade_id:'662', nome:'Caixa d''Água')
    Bairro.find_or_create_by(cidade_id:'662', nome:'Passagem')
    Bairro.find_or_create_by(cidade_id:'662', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'662', nome:'Beira Rio')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Alto do Garrote')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Açude')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Barra Nova')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Bom Jesus')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Cabatan')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Campo Grande')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Camurupim')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Capuan')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Cigana')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Cipó')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Conjunto Metropolitano')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Cumbuco')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Curicaca')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Garrote')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Genipabu')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Grilo')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Guagiru')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Icaraí')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Iparana')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Itambé')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Itapoã')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Jandaiguaba')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Jardim Icaraí')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Lagoa do Banana')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Lagoa dos Porcos')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Lago Verde')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Mestre Antônio')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Nova Cigana')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Novo Pabussu')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Pabussu')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Pacheco')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Padre Júlio Maria')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Padre Romualdo')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Parque Leblon')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Parque Soledade')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Patricia Gomes')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Paumirim')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Planalto Caucaia')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Sobradinho')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Tabapuá')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Tabapuá Brasília')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Tabuba')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Toco')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Urucutuba')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Caraúbas')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Araturi')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Nova Metrópole')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Marechal Rondon')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Arianópolis')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Parque Albano')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Parque das Nações')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Parque Guadalajara')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Parque Potira')
    Bairro.find_or_create_by(cidade_id:'663', nome:'São Miguel')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Tabapuá - Brasília II')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Vila Operária')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Montividéu')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Prado')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Açude Novo')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Alto do Padeiro')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Planalto do Cadeiras')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Açude Velho')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Planalto dos lemos')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Pega Avoante')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Divisão')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Conjunto Habitacional')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Fátima')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Alto da Floresta')
    Bairro.find_or_create_by(cidade_id:'664', nome:'Jardim Afonso Celso')
    Bairro.find_or_create_by(cidade_id:'668', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'668', nome:'São Miguel')
    Bairro.find_or_create_by(cidade_id:'668', nome:'José Gomes Damasceno')
    Bairro.find_or_create_by(cidade_id:'668', nome:'Padre José Maria Aguiar')
    Bairro.find_or_create_by(cidade_id:'668', nome:'Dom Benedito')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Cidade Nova')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Patriarcas')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Cidade 2000')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Cajás')
    Bairro.find_or_create_by(cidade_id:'669', nome:'José Rosa')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Venâncio')
    Bairro.find_or_create_by(cidade_id:'669', nome:'São Vicente')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Ipase')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Maratoan')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Santa Luzia')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Campo Velho')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Nova Terra')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Planalto')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Fátima II')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Fátima I')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Altamira')
    Bairro.find_or_create_by(cidade_id:'669', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'669', nome:'Ponte Preta')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Pimenta')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Seminário')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Vila Alta')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Palmeiral')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Pinto Madeira Vermelho')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Alto da Penha')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Ossian Araripe - Caixa D''Água')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Sossego')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Novo Crato')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Cacimbas')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Parque Recreio')
    Bairro.find_or_create_by(cidade_id:'670', nome:'São Miguel')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Santa Luzia')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Mirandão')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Lobo - Vila Lobo')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Parque Granjeiro')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Novo Horizonte')
    Bairro.find_or_create_by(cidade_id:'670', nome:'José Araújo - Novo Lameiro')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Zacarias Gonçalves')
    Bairro.find_or_create_by(cidade_id:'670', nome:'França Alencar')
    Bairro.find_or_create_by(cidade_id:'670', nome:'São Gonçalo')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Gizélia Pinheiro - Batateiras')
    Bairro.find_or_create_by(cidade_id:'670', nome:'São Bento')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Muriti')
    Bairro.find_or_create_by(cidade_id:'670', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Barro Branco')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Coqueiro')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Lameiro')
    Bairro.find_or_create_by(cidade_id:'670', nome:'Granjeiro')
    Bairro.find_or_create_by(cidade_id:'671', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'671', nome:'Caroba')
    Bairro.find_or_create_by(cidade_id:'674', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'674', nome:'Francisco Nogueira de Queiroz')
    Bairro.find_or_create_by(cidade_id:'674', nome:'Ipiranga')
    Bairro.find_or_create_by(cidade_id:'674', nome:'José Pessoa de Queiroz Moura - José Moura')
    Bairro.find_or_create_by(cidade_id:'676', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'676', nome:'Boa Vista')
    Bairro.find_or_create_by(cidade_id:'676', nome:'Nova Esperança')
    Bairro.find_or_create_by(cidade_id:'677', nome:'Antonio Ferreira Gomes Martins')
    Bairro.find_or_create_by(cidade_id:'677', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'677', nome:'Francisco Martins Viana')
    Bairro.find_or_create_by(cidade_id:'677', nome:'Edmundo Rodrigues')
    Bairro.find_or_create_by(cidade_id:'677', nome:'Alto Alegre')
    Bairro.find_or_create_by(cidade_id:'677', nome:'Mesquita Jerônimo')
    Bairro.find_or_create_by(cidade_id:'677', nome:'José Raimundo de Loiola')
    Bairro.find_or_create_by(cidade_id:'677', nome:'Padre Edson')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Alagadiço')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Aldeota')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Álvaro Weyne')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Amadeo Furtado')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Arraial Moura Brasil')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Barra do Ceará')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Benfica')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Bom Futuro')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Carlito Pamplona')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Coco')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Cristo Redentor')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Damas')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Estância - Dionísio Torres')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Farias Brito')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Fátima')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Floresta')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Jacarecanga')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Jardim América')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Jardim Guanabara')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Jardim Iracema')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Joaquim Távora')
    Bairro.find_or_create_by(cidade_id:'678', nome:'José Bonifácio')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Meireles')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Monte Castelo')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Mucuripe')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Papicu')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parque Araxá')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parquelândia')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parreão')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Pirambú')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Praia de Iracema')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Presidente Kennedy')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Rodolfo Teófilo')
    Bairro.find_or_create_by(cidade_id:'678', nome:'São João do Tauapé')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Varjota')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Vicente Pinzon')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Vila Ellery')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Vila Velha')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Antônio Bezerra')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Autran Nunes')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Conjunto Ceará I')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Dom Lustosa')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Genibau')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Henrique Jorge')
    Bairro.find_or_create_by(cidade_id:'678', nome:'João XXIII')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Padre Andrade - Cachoeirinha')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Quintino Cunha')
    Bairro.find_or_create_by(cidade_id:'678', nome:'José de Alencar')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Ancuri')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Barroso')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Cajazeiras')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Cambeba')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Cidade dos Funcionários')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Coaçu')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Curió')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Edson Queiroz')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Engenheiro Luciano Cavalcante')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Guajeru')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Guarapes')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Jangurussu')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Jardim das Oliveiras')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Lagoa Redonda')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Lagoa Sapiranga - Coité')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Messejana - sede')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parque Iracema')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parque Manibura')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Paupina')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Pedras')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Sabiaguaba')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Salinas')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Bom Jardim')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Bonsucesso')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Canindezinho')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Conjunto Ceará II')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Conjunto Esperança')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Dendê')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Granja Lisboa')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Granja Portugal')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Jardim Cearense')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Manoel Sátiro')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Maraponga')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Mondubim - Sede')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parque Dois Irmãos')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parque Presidente Vargas')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parque São José')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parque Santa Rosa - Apolo XI')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Passaré')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Prefeito José Walter')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Siqueira')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Aerolândia')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Aeroporto - Base Aérea')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Alto da Balança')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Castelão')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Couto Fernades')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Demócrito Rocha')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Dias Macedo')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Itaóca')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Itaperi')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Jóquei Club - São Cristóvão')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Mata Galinha')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Montese')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Pan-Americano')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Parangaba')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Pici - Parque Universitário')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Serrinha')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Vila Pery')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Vila União')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Cais do Porto')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Cidade 2000')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Manuel Dias Branco')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Praia do Futuro I')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Praia do Futuro II')
    Bairro.find_or_create_by(cidade_id:'678', nome:'De Lourdes')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Planalto Ayrton Senna')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Gentilândia')
    Bairro.find_or_create_by(cidade_id:'678', nome:'Conjunto Palmeiras')
    Bairro.find_or_create_by(cidade_id:'678', nome:'São Bento')
    Bairro.find_or_create_by(cidade_id:'681', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'681', nome:'Nossa Senhora das Graças')
    Bairro.find_or_create_by(cidade_id:'681', nome:'Sagrado Coração de Jesus')
    Bairro.find_or_create_by(cidade_id:'681', nome:'Nossa Senhora do Rosário')
    Bairro.find_or_create_by(cidade_id:'684', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'684', nome:'Joaquim Ferreira')
    Bairro.find_or_create_by(cidade_id:'684', nome:'Salomé')
    Bairro.find_or_create_by(cidade_id:'684', nome:'Miguel Saraiva')
    Bairro.find_or_create_by(cidade_id:'685', nome:'Padre Mororó')
    Bairro.find_or_create_by(cidade_id:'685', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'685', nome:'Paulo Malaquias')
    Bairro.find_or_create_by(cidade_id:'685', nome:'José Cassiano')
    Bairro.find_or_create_by(cidade_id:'685', nome:'Capitão José Linhares')
    Bairro.find_or_create_by(cidade_id:'685', nome:'Chico Jerônimo')
    Bairro.find_or_create_by(cidade_id:'686', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'686', nome:'Miguel de Sousa Martins')
    Bairro.find_or_create_by(cidade_id:'686', nome:'Pinheiro')
    Bairro.find_or_create_by(cidade_id:'686', nome:'Helder Eduardo Bezerra')
    Bairro.find_or_create_by(cidade_id:'686', nome:'Dezessete de Março')
    Bairro.find_or_create_by(cidade_id:'686', nome:'Francisco de Goes')
    Bairro.find_or_create_by(cidade_id:'686', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'686', nome:'Maria de Jesus')
    Bairro.find_or_create_by(cidade_id:'686', nome:'Accioly')
    Bairro.find_or_create_by(cidade_id:'689', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'689', nome:'Nova Hidrolândia')
    Bairro.find_or_create_by(cidade_id:'689', nome:'Professora Mirian Ferreira')
    Bairro.find_or_create_by(cidade_id:'689', nome:'Beira Rio')
    Bairro.find_or_create_by(cidade_id:'689', nome:'Progresso')
    Bairro.find_or_create_by(cidade_id:'689', nome:'Marinho')
    Bairro.find_or_create_by(cidade_id:'689', nome:'Mororó')
    Bairro.find_or_create_by(cidade_id:'691', nome:'Alto da Bela Vista')
    Bairro.find_or_create_by(cidade_id:'691', nome:'Campo Velho')
    Bairro.find_or_create_by(cidade_id:'691', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'691', nome:'Nova Ibaretama')
    Bairro.find_or_create_by(cidade_id:'691', nome:'Nossa Senhora Auxiliadora')
    Bairro.find_or_create_by(cidade_id:'691', nome:'Raimunda Emilia')
    Bairro.find_or_create_by(cidade_id:'692', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'692', nome:'José Avelino Portela')
    Bairro.find_or_create_by(cidade_id:'692', nome:'Francisco Custodio de Azevedo')
    Bairro.find_or_create_by(cidade_id:'692', nome:'São João')
    Bairro.find_or_create_by(cidade_id:'692', nome:'Raimundo Linhares')
    Bairro.find_or_create_by(cidade_id:'692', nome:'Padre Pontes')
    Bairro.find_or_create_by(cidade_id:'692', nome:'Vicente Aragão')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Alto do Jucá')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Areias I')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Areias II')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Bastiana')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Bugi')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Cajazeiras')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Cerâmica')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Cocobó')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Cohab')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Chapadinha')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Conjunto Industrial')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Das Flores')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Esplanada I')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Esplanada II')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Jardim Iguatu')
    Bairro.find_or_create_by(cidade_id:'696', nome:'João Paulo')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Planalto')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Poço Comprido')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Prado')
    Bairro.find_or_create_by(cidade_id:'696', nome:'São Sebastião')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Sete de Setembro')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Taboleiro')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Veneza')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Vila Brasília')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Vila Centenário')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Vila Cidão')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Vila Moura')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Vila Neuma')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Vila Santo Antônio')
    Bairro.find_or_create_by(cidade_id:'696', nome:'Paraná')
    Bairro.find_or_create_by(cidade_id:'697', nome:'Boa Esperança')
    Bairro.find_or_create_by(cidade_id:'697', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'697', nome:'Cohab I')
    Bairro.find_or_create_by(cidade_id:'697', nome:'Cohab II')
    Bairro.find_or_create_by(cidade_id:'697', nome:'Liberdade')
    Bairro.find_or_create_by(cidade_id:'697', nome:'Liberdade II')
    Bairro.find_or_create_by(cidade_id:'697', nome:'Pelo Sinal')
    Bairro.find_or_create_by(cidade_id:'697', nome:'Placa')
    Bairro.find_or_create_by(cidade_id:'697', nome:'São Vicente')
    Bairro.find_or_create_by(cidade_id:'698', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'698', nome:'Águas Belas')
    Bairro.find_or_create_by(cidade_id:'698', nome:'Alto do Bom Princípio')
    Bairro.find_or_create_by(cidade_id:'698', nome:'Central')
    Bairro.find_or_create_by(cidade_id:'698', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Aldeota')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Alto dos Quatorze')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Boa Vista')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Berguedorf')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Cafute')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Canudos')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Escondido')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Macaco')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Mina')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Pedrinhas')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Pereiros')
    Bairro.find_or_create_by(cidade_id:'700', nome:'Reino de França')
    Bairro.find_or_create_by(cidade_id:'702', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'702', nome:'Beira Rio')
    Bairro.find_or_create_by(cidade_id:'702', nome:'Pedra Bola')
    Bairro.find_or_create_by(cidade_id:'702', nome:'Jatobá')
    Bairro.find_or_create_by(cidade_id:'702', nome:'Da Paz')
    Bairro.find_or_create_by(cidade_id:'702', nome:'Holandino')
    Bairro.find_or_create_by(cidade_id:'702', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'702', nome:'Caixa D''Água')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Genezaré')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Angorá')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Vila Machado')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Ponta da Serra')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Santo Antônio')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Antônio Miguel')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Riachão')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Ancuri')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Barrocão')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Caracanga')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Carapió')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Gereraú')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Jabuti')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Jibóia')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Laje dos Gatos')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Ocupação')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Pedras')
    Bairro.find_or_create_by(cidade_id:'705', nome:'Vila Nova')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Alto Alegre')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Área Nobre')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Boa Vista')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Cacimbas')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Coqueiro')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Cruzeiro')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Estação')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Fazendinha')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Das Flores')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Julho')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Ladeira')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Madalenas')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Maranhão')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Mourão')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Nova Aldeota')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Picos')
    Bairro.find_or_create_by(cidade_id:'707', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'707', nome:'São Sebastião')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Senharão')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Urbano Teixeira')
    Bairro.find_or_create_by(cidade_id:'707', nome:'Violete')
    Bairro.find_or_create_by(cidade_id:'710', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Padre Sebastião Marleno')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Beira Rio')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Nossa Senhora da Conceição')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Jaime Costa Pinheiro')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Aloísio Diógenes')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Celso Barreira Filho')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Luiz Pinto')
    Bairro.find_or_create_by(cidade_id:'713', nome:'Antônio Duarte')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'715', nome:'João Pereira de Sousa')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Urias Novais')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Olavo Napoleão de Araújo')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Décio Sampaio Couto')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Nossa Senhora de Fátima')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Clodoaldo Xavier Sampaio')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Lourival Gondim')
    Bairro.find_or_create_by(cidade_id:'715', nome:'José Franco Neves - Zé Neves')
    Bairro.find_or_create_by(cidade_id:'715', nome:'João Neves da Luz - João da Luz')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Santa Terezinha')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Otoni de Sá Roriz')
    Bairro.find_or_create_by(cidade_id:'715', nome:'Frei Damião')
    Bairro.find_or_create_by(cidade_id:'716', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'716', nome:'Matulão')
    Bairro.find_or_create_by(cidade_id:'716', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'716', nome:'Portal de Santana')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Juvêncio Santana')
    Bairro.find_or_create_by(cidade_id:'718', nome:'São Miguel')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Carité')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Fátima')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Pedrinhas')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Aeroporto')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Brejo Seco')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Betolândia')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Novo Juazeiro')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Leandro Bezerra de Menezes')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Timbaúba')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Pio XII')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Franciscanos')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Limoeiro')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Pirajá')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Romeirão')
    Bairro.find_or_create_by(cidade_id:'718', nome:'João Cabral')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Triângulo')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Antônio Vieira')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Santa Teresa')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Salesianos')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Socorro')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Salgadinho')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Horto')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Três-Marias')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Planalto')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Lagoa Seca')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Jardim Gonzaga')
    Bairro.find_or_create_by(cidade_id:'718', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'718', nome:'José Geraldo da Cruz')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Tiradentes')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Campo Alegre')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Cidade Universitária')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Frei Damião')
    Bairro.find_or_create_by(cidade_id:'718', nome:'Santo Antonio')
    Bairro.find_or_create_by(cidade_id:'719', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'719', nome:'Nossa Senhora de Fátima')
    Bairro.find_or_create_by(cidade_id:'719', nome:'São Mateus')
    Bairro.find_or_create_by(cidade_id:'719', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'719', nome:'Planalto')
    Bairro.find_or_create_by(cidade_id:'719', nome:'Alto da Paz')
    Bairro.find_or_create_by(cidade_id:'719', nome:'Côco Verde')
    Bairro.find_or_create_by(cidade_id:'719', nome:'Alto do Tó')
    Bairro.find_or_create_by(cidade_id:'719', nome:'Sagrada Família')
    Bairro.find_or_create_by(cidade_id:'719', nome:'Padre Manoel Lemos Braga')
    Bairro.find_or_create_by(cidade_id:'720', nome:'Coronel Raimundo Augusto Lima')
    Bairro.find_or_create_by(cidade_id:'720', nome:'Coronel Francisco Correia Lima')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Ilha')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Luiz Alves de Freitas')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Boa Fé')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Bom nome')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Santa Luzia')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Monsenhor Otávio')
    Bairro.find_or_create_by(cidade_id:'721', nome:'João XXIII')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Doutor José Simões')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Pitombeira')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Brotolândia')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Socorro')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Limoeirinho')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Bom Jesus')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Antônio Holanda')
    Bairro.find_or_create_by(cidade_id:'721', nome:'Bom Jesus do Cruzeiro')
    Bairro.find_or_create_by(cidade_id:'722', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'722', nome:'Henrique Jorge')
    Bairro.find_or_create_by(cidade_id:'722', nome:'Santa Terezinha')
    Bairro.find_or_create_by(cidade_id:'722', nome:'Nova Madalena')
    Bairro.find_or_create_by(cidade_id:'722', nome:'Pinhos')
    Bairro.find_or_create_by(cidade_id:'722', nome:'Antônio Firmino de Pinho')
    Bairro.find_or_create_by(cidade_id:'722', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'722', nome:'Boa Vista')
    Bairro.find_or_create_by(cidade_id:'722', nome:'Santana')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Parque Piratininga')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Coqueiral')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Novo Maracanaú')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Distrito Industrial do Ceará')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Conjunto Timbó')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jereissati Setor C')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jereissati Setor B')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jereissati Setor A')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jereissati Setor D')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jereissati Setor E')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Independência')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Boa Vista')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Alto da Mangueira')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Picada')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Carneiro de Mendonça')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Olho-D''Água do Pitaguari')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Furna da Onça')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Antônio Justa')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Parque Luzardo Viana')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Pau Serrado')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Mucunã')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Cágado')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jaçanau')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Tijuca')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Alto Alegre')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jari')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jatobá')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Siqueira')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Parque Santa Maria')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Alto Alegre I')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Alto Alegre II')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Novo Oriente')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Acaracuzinho I')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Acaracuzinho II')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Esplanada do Mondubim')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Pajuçara')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Boa Esperança')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jardim Paraíso')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Alto da Bonança')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Arronches')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Parque Progresso')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Parque Tropical')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Jardim Bandeirante')
    Bairro.find_or_create_by(cidade_id:'723', nome:'Novo Mondubim')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Outra Banda')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Preguiça')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Pirapora')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Gavião')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Guabiraba')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Parque Santa Fé')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Aldeoma')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Parque São João')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Tangueira')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Coité')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Parque Iracema')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Santos Dumont')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Novo Parque Iracema')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Lameirão')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Urucara')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Novo Maranguape I')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Novo Maranguape II')
    Bairro.find_or_create_by(cidade_id:'724', nome:'Cônego Raimundo Pinto')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Ginásio')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Cartucha')
    Bairro.find_or_create_by(cidade_id:'727', nome:'São João')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Nossa Senhora de Fátima')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Cruzeiro')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Bandeira Branca')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Usina Velha')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Alto da Boa Vista')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Joaquim Marques')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Alto da Cadeia')
    Bairro.find_or_create_by(cidade_id:'727', nome:'Santa Úrsula')
    Bairro.find_or_create_by(cidade_id:'728', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'728', nome:'Nossa Senhora de Fátima')
    Bairro.find_or_create_by(cidade_id:'728', nome:'Dantas')
    Bairro.find_or_create_by(cidade_id:'728', nome:'Nova Mauriti')
    Bairro.find_or_create_by(cidade_id:'728', nome:'Populares')
    Bairro.find_or_create_by(cidade_id:'728', nome:'Monte Alegre')
    Bairro.find_or_create_by(cidade_id:'728', nome:'Bela Vista II')
    Bairro.find_or_create_by(cidade_id:'728', nome:'Bela Vista I')
    Bairro.find_or_create_by(cidade_id:'728', nome:'Dom Bosco')
    Bairro.find_or_create_by(cidade_id:'728', nome:'César Nascimento')
    Bairro.find_or_create_by(cidade_id:'728', nome:'José Silcon de Lacerda')
    Bairro.find_or_create_by(cidade_id:'729', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'729', nome:'Divino Salvador')
    Bairro.find_or_create_by(cidade_id:'729', nome:'Dom Expedito')
    Bairro.find_or_create_by(cidade_id:'729', nome:'Coronel Bezerril')
    Bairro.find_or_create_by(cidade_id:'730', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'730', nome:'Eucaliptos')
    Bairro.find_or_create_by(cidade_id:'730', nome:'Casa Própria')
    Bairro.find_or_create_by(cidade_id:'730', nome:'Francisca do Socorro')
    Bairro.find_or_create_by(cidade_id:'730', nome:'Frei Damião')
    Bairro.find_or_create_by(cidade_id:'730', nome:'Rodoviário')
    Bairro.find_or_create_by(cidade_id:'730', nome:'das Missionárias')
    Bairro.find_or_create_by(cidade_id:'730', nome:'Padre Cícero')
    Bairro.find_or_create_by(cidade_id:'733', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'733', nome:'Antonio Linard')
    Bairro.find_or_create_by(cidade_id:'733', nome:'Lordival Januário Pereira')
    Bairro.find_or_create_by(cidade_id:'733', nome:'da Fé')
    Bairro.find_or_create_by(cidade_id:'733', nome:'Nelson Cândido de Macedo')
    Bairro.find_or_create_by(cidade_id:'733', nome:'José de Iaiá')
    Bairro.find_or_create_by(cidade_id:'733', nome:'Adalberto Casimiro de Farias')
    Bairro.find_or_create_by(cidade_id:'733', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'733', nome:'Rubens Arrais Maia')
    Bairro.find_or_create_by(cidade_id:'733', nome:'Novo Milênio')
    Bairro.find_or_create_by(cidade_id:'733', nome:'Antonio Luiz')
    Bairro.find_or_create_by(cidade_id:'733', nome:'José Pimenta')
    Bairro.find_or_create_by(cidade_id:'734', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'734', nome:'Tejubana')
    Bairro.find_or_create_by(cidade_id:'734', nome:'Vila Iracema')
    Bairro.find_or_create_by(cidade_id:'734', nome:'Antônio Felinto')
    Bairro.find_or_create_by(cidade_id:'734', nome:'Vila Salete')
    Bairro.find_or_create_by(cidade_id:'734', nome:'Vila São José')
    Bairro.find_or_create_by(cidade_id:'734', nome:'Vila Recreio')
    Bairro.find_or_create_by(cidade_id:'734', nome:'Vila Betânia')
    Bairro.find_or_create_by(cidade_id:'735', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'735', nome:'Trizidela')
    Bairro.find_or_create_by(cidade_id:'735', nome:'Quadra')
    Bairro.find_or_create_by(cidade_id:'735', nome:'Alto da Boa Vista')
    Bairro.find_or_create_by(cidade_id:'735', nome:'Prado')
    Bairro.find_or_create_by(cidade_id:'735', nome:'Jucás')
    Bairro.find_or_create_by(cidade_id:'735', nome:'Lilio Gentil Leitão')
    Bairro.find_or_create_by(cidade_id:'735', nome:'Carrapicho')
    Bairro.find_or_create_by(cidade_id:'742', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'742', nome:'Água Boa')
    Bairro.find_or_create_by(cidade_id:'742', nome:'Progresso')
    Bairro.find_or_create_by(cidade_id:'742', nome:'Timbaúba')
    Bairro.find_or_create_by(cidade_id:'742', nome:'Tamarindo')
    Bairro.find_or_create_by(cidade_id:'742', nome:'Alto da Boa Vista')
    Bairro.find_or_create_by(cidade_id:'742', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'742', nome:'Patronato')
    Bairro.find_or_create_by(cidade_id:'742', nome:'Universidade')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Prefeito Manoel Claudino Sales')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Boa Vista')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Colinas')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Açude Oriente II')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Açude Oriente I')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Vila Feliz')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Lagoa do Tigre Sul')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Lagoa do Tigre Norte')
    Bairro.find_or_create_by(cidade_id:'743', nome:'João Antero')
    Bairro.find_or_create_by(cidade_id:'743', nome:'Vicente Rodrigues Vieira')
    Bairro.find_or_create_by(cidade_id:'747', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'747', nome:'Carnaubinha')
    Bairro.find_or_create_by(cidade_id:'747', nome:'Pracinha')
    Bairro.find_or_create_by(cidade_id:'747', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'747', nome:'Forquilha')
    Bairro.find_or_create_by(cidade_id:'747', nome:'Parque Aratanha')
    Bairro.find_or_create_by(cidade_id:'747', nome:'São Bento')
    Bairro.find_or_create_by(cidade_id:'747', nome:'Alto São João')
    Bairro.find_or_create_by(cidade_id:'749', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'749', nome:'Bananeira')
    Bairro.find_or_create_by(cidade_id:'749', nome:'Barro Branco')
    Bairro.find_or_create_by(cidade_id:'751', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'751', nome:'Vinte e Oito de Agosto')
    Bairro.find_or_create_by(cidade_id:'751', nome:'Bica')
    Bairro.find_or_create_by(cidade_id:'751', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'751', nome:'Vila Campos')
    Bairro.find_or_create_by(cidade_id:'751', nome:'Caboclos')
    Bairro.find_or_create_by(cidade_id:'754', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'754', nome:'Beleza')
    Bairro.find_or_create_by(cidade_id:'754', nome:'Planalto')
    Bairro.find_or_create_by(cidade_id:'754', nome:'Horácio Alves Noronha')
    Bairro.find_or_create_by(cidade_id:'754', nome:'Brasília')
    Bairro.find_or_create_by(cidade_id:'754', nome:'Caixa d''Água')
    Bairro.find_or_create_by(cidade_id:'754', nome:'Cachimbo')
    Bairro.find_or_create_by(cidade_id:'754', nome:'Vila Nova')
    Bairro.find_or_create_by(cidade_id:'755', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'755', nome:'Vicente Farias')
    Bairro.find_or_create_by(cidade_id:'755', nome:'Arrudas')
    Bairro.find_or_create_by(cidade_id:'755', nome:'Esplanada do Conjunto')
    Bairro.find_or_create_by(cidade_id:'755', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'756', nome:'Boa Esperança')
    Bairro.find_or_create_by(cidade_id:'756', nome:'Bom Princípio')
    Bairro.find_or_create_by(cidade_id:'756', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'756', nome:'Chico Leandro')
    Bairro.find_or_create_by(cidade_id:'756', nome:'Padre Geraldo')
    Bairro.find_or_create_by(cidade_id:'756', nome:'Riso do Prado')
    Bairro.find_or_create_by(cidade_id:'756', nome:'Santa Maria')
    Bairro.find_or_create_by(cidade_id:'756', nome:'Santa Úrsula')
    Bairro.find_or_create_by(cidade_id:'757', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'757', nome:'Frei Damião')
    Bairro.find_or_create_by(cidade_id:'757', nome:'Nossa Senhora Aparecida')
    Bairro.find_or_create_by(cidade_id:'757', nome:'Padre Cícero')
    Bairro.find_or_create_by(cidade_id:'761', nome:'Armando Melo')
    Bairro.find_or_create_by(cidade_id:'761', nome:'Alto do Bentivi')
    Bairro.find_or_create_by(cidade_id:'761', nome:'Alto do Bumerang')
    Bairro.find_or_create_by(cidade_id:'761', nome:'Alto dos Maias')
    Bairro.find_or_create_by(cidade_id:'761', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'761', nome:'João Paulo II')
    Bairro.find_or_create_by(cidade_id:'761', nome:'Piquezinho')
    Bairro.find_or_create_by(cidade_id:'761', nome:'Rancho Verde')
    Bairro.find_or_create_by(cidade_id:'763', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'763', nome:'Aeroporto')
    Bairro.find_or_create_by(cidade_id:'763', nome:'Erasino Neto')
    Bairro.find_or_create_by(cidade_id:'763', nome:'Betânia')
    Bairro.find_or_create_by(cidade_id:'763', nome:'Jericó')
    Bairro.find_or_create_by(cidade_id:'763', nome:'Jardim das Oliveiras')
    Bairro.find_or_create_by(cidade_id:'764', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'764', nome:'José Aristarco Cardoso')
    Bairro.find_or_create_by(cidade_id:'764', nome:'Sol Nascente')
    Bairro.find_or_create_by(cidade_id:'764', nome:'José Irapuan Tavares de Lavor')
    Bairro.find_or_create_by(cidade_id:'764', nome:'Entre Rios')
    Bairro.find_or_create_by(cidade_id:'764', nome:'Campo Santo')
    Bairro.find_or_create_by(cidade_id:'764', nome:'Imaculada Conceição')
    Bairro.find_or_create_by(cidade_id:'765', nome:'Vila Campo')
    Bairro.find_or_create_by(cidade_id:'765', nome:'Vila Padre Cícero')
    Bairro.find_or_create_by(cidade_id:'765', nome:'Vila Andrade')
    Bairro.find_or_create_by(cidade_id:'765', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'765', nome:'Guaribas')
    Bairro.find_or_create_by(cidade_id:'765', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'766', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'766', nome:'Trapiá')
    Bairro.find_or_create_by(cidade_id:'766', nome:'Pedro Paulino de Freitas')
    Bairro.find_or_create_by(cidade_id:'766', nome:'Manoel Dantas de Almeida')
    Bairro.find_or_create_by(cidade_id:'767', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'767', nome:'Alto Brilhante')
    Bairro.find_or_create_by(cidade_id:'767', nome:'Cidade Nova')
    Bairro.find_or_create_by(cidade_id:'767', nome:'Colinas')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Alto da Boa Vista')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Alto São Francisco')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Baviera')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Boto')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Campo Novo')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Campo Velho')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Carrascal')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Cohab')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Combate')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Curicaca')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Herval')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Irajá')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Jardim dos Monólitos')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Monte Alegre')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Nova Jerusalém')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Planalto Renascer')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Planalto Universitário')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Putiú')
    Bairro.find_or_create_by(cidade_id:'768', nome:'São João')
    Bairro.find_or_create_by(cidade_id:'768', nome:'Triângulo')
    Bairro.find_or_create_by(cidade_id:'771', nome:'Pontal')
    Bairro.find_or_create_by(cidade_id:'771', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'771', nome:'Leão')
    Bairro.find_or_create_by(cidade_id:'771', nome:'Nova Morada')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Tabuleiro da Vaquejada')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Tabuleiro do Catavento')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Várzea Alegre')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Vila Ramalho')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Nossa Senhora de Fátima')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Vila Gonçalves')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Vila Matoso')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Alto do Velame')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Pitombeira')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Ipiranga')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Planalto da Catumbela')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Planalto da Bela Vista')
    Bairro.find_or_create_by(cidade_id:'774', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'778', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'778', nome:'Alto da Liberdade')
    Bairro.find_or_create_by(cidade_id:'778', nome:'Pedregal')
    Bairro.find_or_create_by(cidade_id:'778', nome:'Jericó')
    Bairro.find_or_create_by(cidade_id:'778', nome:'Gerardo Arcanjo')
    Bairro.find_or_create_by(cidade_id:'778', nome:'Retiro')
    Bairro.find_or_create_by(cidade_id:'778', nome:'João Alfredo')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Centro ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Luis Demerval de Andrade ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Raimundo Mesquita Sobrinho ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'José Ernane Catunda Sales ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Pedra da Saudade ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Dr. Afonso Walter M. Pinto ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Diro Moreira ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Flores ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Edson Lobo de Mesquita ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Planalto da Piracicaba ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Senador Francisco Menezes Pimentel ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Primavera ')
    Bairro.find_or_create_by(cidade_id:'777', nome:'Boa Vida ')
    Bairro.find_or_create_by(cidade_id:'782', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'782', nome:'Pacheco')
    Bairro.find_or_create_by(cidade_id:'782', nome:'Velosa')
    Bairro.find_or_create_by(cidade_id:'782', nome:'Bela Vista')
    Bairro.find_or_create_by(cidade_id:'782', nome:'João Candido')
    Bairro.find_or_create_by(cidade_id:'785', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'785', nome:'Nossa Senhora do Amparo')
    Bairro.find_or_create_by(cidade_id:'785', nome:'Nossa Senhora do Carmo')
    Bairro.find_or_create_by(cidade_id:'785', nome:'Pitombeiras')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Sumaré')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Dom José')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Domingos Olímpio')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Cidade Dr. José Euclides Ferreira Gomes Júnior')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Alto Cristo')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Junco')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Campo dos Velhos')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Parque Silvana')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Colina da Boa Vista')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Da Expectativa')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Coração de Jesus')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Alto Brasília')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Jerônimo de Medeiros Prado')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Derby Clube')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Pedrinhas')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Várzea Grande')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Cohab II')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Cohab I')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Jatobá')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Sinhá Sabóia')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Dom Expedito')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Distrito Industrial')
    Bairro.find_or_create_by(cidade_id:'786', nome:'Padre Ibiapina')
    Bairro.find_or_create_by(cidade_id:'788', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'788', nome:'José Mendes')
    Bairro.find_or_create_by(cidade_id:'788', nome:'8 de Setembro')
    Bairro.find_or_create_by(cidade_id:'788', nome:'Água Santa')
    Bairro.find_or_create_by(cidade_id:'788', nome:'Bom Futuro')
    Bairro.find_or_create_by(cidade_id:'788', nome:'Macena')
    Bairro.find_or_create_by(cidade_id:'788', nome:'São Vicente')
    Bairro.find_or_create_by(cidade_id:'788', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'788', nome:'Joaquim Fernandes Colares')
    Bairro.find_or_create_by(cidade_id:'788', nome:'Lula')
    Bairro.find_or_create_by(cidade_id:'788', nome:'8 de Junho')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Monsenhor Holanda')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Monte Azul')
    Bairro.find_or_create_by(cidade_id:'789', nome:'das Pedrinhas')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Monte Castelo')
    Bairro.find_or_create_by(cidade_id:'789', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'789', nome:'São Pedro')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Antonio Mota Filho')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Areias')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Bola Branca')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Jardim América')
    Bairro.find_or_create_by(cidade_id:'789', nome:'Poço Escuro')
    Bairro.find_or_create_by(cidade_id:'789', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Luiz Antônio de Oliveira Sousa')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Cidade Nova')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Manoel Alves Mota')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Bezerra de Sousa')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Nova Aldeota')
    Bairro.find_or_create_by(cidade_id:'791', nome:'dos Colibris')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Alto do Cruzeiro')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Tauazinho')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Alto Brilhante')
    Bairro.find_or_create_by(cidade_id:'791', nome:'José Alexandrino Nogueira')
    Bairro.find_or_create_by(cidade_id:'791', nome:'José Holanda Lima')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Francisco Soares de Carvalho')
    Bairro.find_or_create_by(cidade_id:'791', nome:'Sebastião César Rêgo')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Boa Esperança I')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Carnaúba Torta')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Boa Esperança II')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Cotesa')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Ilha')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Planalto Norte')
    Bairro.find_or_create_by(cidade_id:'794', nome:'São Francisco')
    Bairro.find_or_create_by(cidade_id:'794', nome:'São Gonçalo')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Serrinha')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Vila Nova')
    Bairro.find_or_create_by(cidade_id:'794', nome:'São José')
    Bairro.find_or_create_by(cidade_id:'794', nome:'Volta do "S"')
    Bairro.find_or_create_by(cidade_id:'800', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'800', nome:'Brasília')
    Bairro.find_or_create_by(cidade_id:'800', nome:'Roberto Dourado')
    Bairro.find_or_create_by(cidade_id:'800', nome:'Nossa Senhora do Livramento')
    Bairro.find_or_create_by(cidade_id:'800', nome:'26 de Março')
    Bairro.find_or_create_by(cidade_id:'800', nome:'Alecrim')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Centro')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Juremal')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Sanharol')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Varzante')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Praça Santo Antonio')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Betânia')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Grossos')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Brejinho dos Vieiras')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Dona Rosinha')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Patos')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Riachinho')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Buenos Aires')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Serrinha')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Zezinho Costa')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Varjota')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Baixio do Exu')
    Bairro.find_or_create_by(cidade_id:'802', nome:'Alto do Tenente')
    Bairro.find_or_create_by(cidade_id:'663', nome:'Jurema')
    puts "Fim importação de bairros ..."
  end
end