json.extract! socioeduk_saude_jovens_tipo_medicamento_controlado, :id, :socioeduk_saude_jovens_id, :socioeduk_tipo_medicamento_controlado_id, :created_at, :updated_at
json.url socioeduk_saude_jovens_tipo_medicamento_controlado_url(socioeduk_saude_jovens_tipo_medicamento_controlado, format: :json)
