# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe CategoriaPatrimoniosController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # CategoriaPatrimonio. As you add validations to CategoriaPatrimonio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { nome: 'NomeValido' }
  end

  let(:invalid_attributes) do
    { nome: '' }
  end

  let(:categoria_patrimonio) do
    @categoria_patrimonio ||= CategoriaPatrimonio.create! valid_attributes
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CategoriaPatrimoniosController. Be sure to keep this updated too.
  stub_sign_in
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'returns a success response' do
      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      get :show, params: { id: categoria_patrimonio.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      get :edit, params: { id: categoria_patrimonio.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new CategoriaPatrimonio' do
        expect do
          post :create, params: { categoria_patrimonio: valid_attributes }, session: valid_session
        end.to change(CategoriaPatrimonio, :count).by(1)
      end

      it 'redirects to the created categoria_patrimonio' do
        post :create, params: { categoria_patrimonio: valid_attributes }, session: valid_session
        expect(response).to redirect_to(categoria_patrimonios_path)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { categoria_patrimonio: invalid_attributes }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        { nome: 'MyText' }
      end

      it 'updates the requested categoria_patrimonio' do
        put :update, params: { id: categoria_patrimonio.to_param, categoria_patrimonio: new_attributes }, session: valid_session
        categoria_patrimonio.reload
        expect(categoria_patrimonio.nome).to be_eql('MyText')
      end

      it 'redirects to the categoria_patrimonio' do
        put :update, params: { id: categoria_patrimonio.to_param, categoria_patrimonio: valid_attributes }, session: valid_session
        expect(response).to redirect_to(categoria_patrimonios_path)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, params: { id: categoria_patrimonio.to_param, categoria_patrimonio: invalid_attributes }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested categoria_patrimonio' do
      categoria_patrimonio = CategoriaPatrimonio.create! valid_attributes
      expect do
        delete :destroy, params: { id: categoria_patrimonio.to_param }, session: valid_session
      end.to change(CategoriaPatrimonio, :count).by(-1)
    end

    it 'redirects to the categoria_patrimonios list' do
      categoria_patrimonio = CategoriaPatrimonio.create! valid_attributes
      delete :destroy, params: { id: categoria_patrimonio.to_param }, session: valid_session
      expect(response).to redirect_to(categoria_patrimonios_url)
    end
  end
end
