# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe PatrimoniosController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Patrimonio. As you add validations to Patrimonio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    status_patrimonio = FactoryBot.create(:status_patrimonio)
    item_patrimonio = FactoryBot.create(:item_patrimonio)
    deposito = FactoryBot.create(:deposito)
    { tombo_anterior: '1234', origem_anterior: 'STDS', tombo_atual: '4321', origem_atual: 'SEAS', status_patrimonio_id: status_patrimonio.id, deposito_id: deposito.id, item_patrimonio_id: item_patrimonio.id }
  end

  let(:invalid_attributes) do
    { tombo_anterior: '', origem_anterior: '', tombo_atual: '', origem_atual: '', status_patrimonio_id: nil, deposito_id: nil, item_patrimonio_id: nil }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PatrimoniosController. Be sure to keep this updated too.
  stub_sign_in
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'returns a success response' do
      patrimonio = Patrimonio.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      patrimonio = Patrimonio.create! valid_attributes
      get :show, params: { id: patrimonio.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      patrimonio = Patrimonio.create! valid_attributes
      get :edit, params: { id: patrimonio.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Patrimonio' do
        expect do
          post :create, params: { patrimonio: valid_attributes }, session: valid_session
        end.to change(Patrimonio, :count).by(1)
      end

      it 'redirects to the created patrimonio' do
        post :create, params: { patrimonio: valid_attributes }, session: valid_session
        expect(response).to redirect_to(patrimonios_path)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { patrimonio: invalid_attributes }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested patrimonio' do
        patrimonio = Patrimonio.create! valid_attributes
        put :update, params: { id: patrimonio.to_param, patrimonio: new_attributes }, session: valid_session
        patrimonio.reload
        status_patrimonio = FactoryBot.create(:status_patrimonio)
        item_patrimonio = FactoryBot.create(:item_patrimonio)
        deposito = FactoryBot.create(:deposito)
        { tombo_anterior: '1234', origem_anterior: 'STDS', tombo_atual: '4321', origem_atual: 'SEAS', status_patrimonio_id: status_patrimonio.id, deposito_id: deposito.id, item_patrimonio_id: item_patrimonio.id }
      end

      it 'redirects to the patrimonio' do
        patrimonio = Patrimonio.create! valid_attributes
        put :update, params: { id: patrimonio.to_param, patrimonio: valid_attributes }, session: valid_session
        expect(response).to redirect_to(patrimonios_path)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        patrimonio = Patrimonio.create! valid_attributes
        put :update, params: { id: patrimonio.to_param, patrimonio: invalid_attributes }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested patrimonio' do
      patrimonio = Patrimonio.create! valid_attributes
      expect do
        delete :destroy, params: { id: patrimonio.to_param }, session: valid_session
      end.to change(Patrimonio, :count).by(-1)
    end

    it 'redirects to the patrimonios list' do
      patrimonio = Patrimonio.create! valid_attributes
      delete :destroy, params: { id: patrimonio.to_param }, session: valid_session
      expect(response).to redirect_to(patrimonios_url)
    end
  end
end
